ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Models/ErrorViewModel.cs
namespace Avenga.TodoApp.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Avenga.TodoApp.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Avenga.TodoApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Controllers/TodoController.cs
using Avenga.TodoApp.Services.Dtos;
using Avenga.TodoApp.Services.Services.Interfaces;
using Avenga.TodoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Avenga.TodoApp.Web.Controllers
{
    public class TodoController : Controller
    {
        private readonly ITodoService _todoService;
        private readonly ICategoryService _categoryService;
        public TodoController(ITodoService todoService, ICategoryService categoryService)
        {
            _todoService = todoService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            List<TodoDto> todos = _todoService.GetAllTodos().ToList();

            return View(todos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateTodoVM createTodoVM = new CreateTodoVM();
            createTodoVM.DueDate = DateTime.Now;
            createTodoVM.Categories = _categoryService.GetAllCategories();
            return View(createTodoVM);
        }

        [HttpPost]
        public IActionResult Create(CreateTodoVM model)
        {
            if (ModelState.IsValid)
            {
                _todoService.AddTodo(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult MarkComplete(int id)
        {
                var response = _todoService.MarkComplete(id);
            if(!response)
            {
                //TempData["ErrorMessage"] = "Todo does not exists!";
                ViewBag.ErrorMessage = "Todo does not exists!";
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult RemoveComplete()
        {
            _todoService.RemoveComplete();
            return RedirectToAction("Index");
        }
    }
}

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avenga.TodoApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Avenga.TodoApp.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My todo app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Avenga.TodoApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Views/Todo/Create.cshtml
@model CreateTodoVM

<div class="container">
    <div class="row">
        <h2>Add todo</h2>
        <div class="col-md-6">
            <form asp-action="Create" asp-controller="Todo" method="post">
                <div>
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-control"/>
                </div>
                <div>
                    <label asp-for="DueDate" class="form-label"></label>
                    <input asp-for="DueDate" class="form-control" />
                </div>
                <div>
                    <label asp-for="CategoryId" class="form-label"></label>
                    <select class="form-select" 
                            asp-for="CategoryId"
                            asp-items="@(new SelectList(Model.Categories, "Id", "Name"))">
                        <option value="0">Select category</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>

ClassCode/Class10/Workshop_p3/Avenga.TodoApp/Avenga.TodoApp.Web/Views/Todo/Index.cshtml
@model List<TodoDto>

<div class="container">
    <div class="row">
        <h2>My Todo list:</h2>
        <div class="col-md-12">
            @if (ViewBag.ErrorMessage is not null)
            {
                <h6 class="alert alert-danger">@ViewBag.ErrorMessage</h6>
            }
            <table class="table table-bordered table-striped mt-2">
                <thead>
                    <tr>
                        <th>
                            <label asp-for="@Model.FirstOrDefault().Description"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.FirstOrDefault().DueDate"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.FirstOrDefault().Category"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.FirstOrDefault().Status"></label>
                        </th>
                        <th class="w-25"></th>
                    </tr>
                </thead>
                <tbody>
                    <form asp-action="MarkComplete" asp-controller="Todo" method="post">
                        @foreach (var todo in Model)
                        {
                            string overdueClass = todo.DueDate.Date < DateTime.Now.Date ? "bg-danger" : "";

                        <tr>
                            <td>@todo.Description</td>
                            <td class="@overdueClass">@todo.DueDate.ToShortDateString()</td>
                            <td>@todo.Category</td>
                            <td>@todo.Status</td>
                            <td>
                                <button type="submit" class="btn btn-outline-primary btn-sm" name="@nameof(TodoDto.Id)" value="@todo.Id">Mark as complete</button>
                            </td>
                        </tr>
                    }
                    </form>
                </tbody>
            </table>
            <div class="row">
                <form asp-action="RemoveComplete" asp-controller="Todo" method="post">
                    <a asp-action="Create" class="btn btn-primary">Add new todo</a>
                    <button type="submit" class="btn btn-outline-danger">Remove all completed</button>
                </form>
            </div>
        </div>
    </div>
</div>